In [1]:
!pip show  polars

Name: polars
Version: 1.35.2
Summary: Blazingly fast DataFrame library
Home-page: https://www.pola.rs/
Author:
Author-email: Ritchie Vink <ritchie46@gmail.com>
License: Copyright (c) 2025 Ritchie Vink
Some portions Copyright (c) 2024 NVIDIA CORPORATION & AFFILIATES. All rights reserved.

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

Location: /home/developer/anaconda3/lib/python3.13/site-packages
Requires: polars-runtime-32
Required-by:

In [2]:
!pip install polars

Collecting polars
  Downloading polars-1.35.2-py3-none-any.whl.metadata (10 kB)
Collecting polars-runtime-32==1.35.2 (from polars)
  Downloading polars_runtime_32-1.35.2-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.5 kB)
Downloading polars-1.35.2-py3-none-any.whl (783 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 783.6/783.6 kB 2.6 MB/s eta 0:00:00[31m11.5 MB/s eta 0:00:01
Downloading polars_runtime_32-1.35.2-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (41.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.3/41.3 MB 10.3 MB/s eta 0:00:00m eta 0:00:01[36m0:00:01
Installing collected packages: polars-runtime-32, polars
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [polars]━━━━ 1/2 [polars]
Successfully installed polars-1.35.2 polars-runtime-32-1.35.2

In [1]:
!pip uninstall polars -y
!pip install polars-lts-cpu

Found existing installation: polars 1.35.2
Uninstalling polars-1.35.2:
  Successfully uninstalled polars-1.35.2
Collecting polars-lts-cpu
  Downloading polars_lts_cpu-1.33.1-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (15 kB)
Downloading polars_lts_cpu-1.33.1-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (39.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 39.6/39.6 MB 9.4 MB/s eta 0:00:000m eta 0:00:01[36m0:00:01
Installing collected packages: polars-lts-cpu
Successfully installed polars-lts-cpu-1.33.1

In [2]:
import polars as pl

In [3]:
lazy_df = pl.scan_csv("data/202306-divvy-tripdata.csv")

In [13]:
lazy_df.head(5).collect()

ComputeError: could not parse `"TA1309000067"` as dtype `i64` at column 'end_station_id' (column number 8)

The current offset in the file is 85050 bytes.

You might want to try:
- increasing `infer_schema_length` (e.g. `infer_schema_length=10000`),
- specifying correct dtype with the `schema_overrides` argument
- setting `ignore_errors` to `True`,
- adding `"TA1309000067"` to the `null_values` list.

Original error: ```remaining bytes non-empty```

In [35]:
lazy_df1 = pl.scan_csv("data/202306-divvy-tripdata.csv", schema_overrides={"end_station_id": pl.Utf8})
lazy_df1.collect()

shape: (999, 13)
┌────────────┬────────────┬────────────┬───────────┬───┬───────────┬─────────┬─────────┬───────────┐
│ ride_id    ┆ rideable_t ┆ started_at ┆ ended_at  ┆ … ┆ start_lng ┆ end_lat ┆ end_lng ┆ member_ca │
│ ---        ┆ ype        ┆ ---        ┆ ---       ┆   ┆ ---       ┆ ---     ┆ ---     ┆ sual      │
│ str        ┆ ---        ┆ str        ┆ str       ┆   ┆ f64       ┆ f64     ┆ f64     ┆ ---       │
│            ┆ str        ┆            ┆           ┆   ┆           ┆         ┆         ┆ str       │
╞════════════╪════════════╪════════════╪═══════════╪═══╪═══════════╪═════════╪═════════╪═══════════╡
│ 6F1682AC40 ┆ electric_b ┆ 2023-06-05 ┆ 2023-06-0 ┆ … ┆ -87.69    ┆ 41.91   ┆ -87.7   ┆ member    │
│ EB6F71     ┆ ike        ┆ 13:34:12   ┆ 5         ┆   ┆           ┆         ┆         ┆           │
│            ┆            ┆            ┆ 14:31:56  ┆   ┆           ┆         ┆         ┆           │
│ 622A1686D6 ┆ electric_b ┆ 2023-06-05 ┆ 2023-06-0 ┆ … ┆ -87.65    ┆ 41.94   ┆ -87.65  ┆ member    │
│ 4948EB     ┆ ike        ┆ 01:30:22   ┆ 5         ┆   ┆           ┆         ┆         ┆           │
│            ┆            ┆            ┆ 01:33:06  ┆   ┆           ┆         ┆         ┆           │
│ 3C88859D92 ┆ electric_b ┆ 2023-06-20 ┆ 2023-06-2 ┆ … ┆ -87.68    ┆ 41.92   ┆ -87.63  ┆ member    │
│ 6253B4     ┆ ike        ┆ 18:15:49   ┆ 0         ┆   ┆           ┆         ┆         ┆           │
│            ┆            ┆            ┆ 18:32:05  ┆   ┆           ┆         ┆         ┆           │
│ EAD8A5E025 ┆ electric_b ┆ 2023-06-19 ┆ 2023-06-1 ┆ … ┆ -87.65    ┆ 41.98   ┆ -87.66  ┆ member    │
│ 9DEC88     ┆ ike        ┆ 14:56:00   ┆ 9         ┆   ┆           ┆         ┆         ┆           │
│            ┆            ┆            ┆ 15:00:35  ┆   ┆           ┆         ┆         ┆           │
│ 5A36F21930 ┆ electric_b ┆ 2023-06-19 ┆ 2023-06-1 ┆ … ┆ -87.66    ┆ 41.99   ┆ -87.65  ┆ member    │
│ D6A55C     ┆ ike        ┆ 15:03:34   ┆ 9         ┆   ┆           ┆         ┆         ┆           │
│            ┆            ┆            ┆ 15:07:16  ┆   ┆           ┆         ┆         ┆           │
│ …          ┆ …          ┆ …          ┆ …         ┆ … ┆ …         ┆ …       ┆ …       ┆ …         │
│ 3B780A995A ┆ electric_b ┆ 2023-06-18 ┆ 2023-06-1 ┆ … ┆ -87.72    ┆ 41.97   ┆ -87.73  ┆ member    │
│ 0219E3     ┆ ike        ┆ 08:32:16   ┆ 8         ┆   ┆           ┆         ┆         ┆           │
│            ┆            ┆            ┆ 08:39:34  ┆   ┆           ┆         ┆         ┆           │
│ 73EAB52DC6 ┆ electric_b ┆ 2023-06-18 ┆ 2023-06-1 ┆ … ┆ -87.67    ┆ 41.92   ┆ -87.68  ┆ member    │
│ 92D9A1     ┆ ike        ┆ 01:07:38   ┆ 8         ┆   ┆           ┆         ┆         ┆           │
│            ┆            ┆            ┆ 01:14:07  ┆   ┆           ┆         ┆         ┆           │
│ EAC18E1F19 ┆ electric_b ┆ 2023-06-17 ┆ 2023-06-1 ┆ … ┆ -87.68    ┆ 41.92   ┆ -87.68  ┆ member    │
│ E5A05B     ┆ ike        ┆ 20:24:58   ┆ 7         ┆   ┆           ┆         ┆         ┆           │
│            ┆            ┆            ┆ 20:25:08  ┆   ┆           ┆         ┆         ┆           │
│ DB04F0278D ┆ electric_b ┆ 2023-06-18 ┆ 2023-06-1 ┆ … ┆ -87.69716 ┆ 41.9    ┆ -87.66  ┆ member    │
│ 4E085B     ┆ ike        ┆ 17:47:30   ┆ 8         ┆   ┆           ┆         ┆         ┆           │
│            ┆            ┆            ┆ 18:01:14  ┆   ┆           ┆         ┆         ┆           │
│ E113CD59DB ┆ electric_b ┆ 2023-06-29 ┆ 2023-06-2 ┆ … ┆ -87.66    ┆ 41.95   ┆ -87.66  ┆ member    │
│ 0D940A     ┆ ike        ┆ 10:24:37   ┆ 9         ┆   ┆           ┆         ┆         ┆           │
│            ┆            ┆            ┆ 10:30:05  ┆   ┆           ┆         ┆         ┆           │
└────────────┴────────────┴────────────┴───────────┴───┴───────────┴─────────┴─────────┴───────────┘

In [36]:
from pyspark.sql import SparkSession
spark = SparkSession.builder.appName("Ex9").getOrCreate()


df = spark.read.csv("data/202306-divvy-tripdata.csv", header=True, inferSchema=True)
df.printSchema()

WARNING: Using incubator modules: jdk.incubator.vector
Using Spark's default log4j profile: org/apache/spark/log4j2-defaults.properties
25/11/11 12:39:25 WARN Utils: Your hostname, developer, resolves to a loopback address: 127.0.1.1; using 192.168.29.9 instead (on interface enp2s0)
25/11/11 12:39:25 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
Using Spark's default log4j profile: org/apache/spark/log4j2-defaults.properties
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
25/11/11 12:39:27 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable

root
 |-- ride_id: string (nullable = true)
 |-- rideable_type: string (nullable = true)
 |-- started_at: timestamp (nullable = true)
 |-- ended_at: timestamp (nullable = true)
 |-- start_station_name: string (nullable = true)
 |-- start_station_id: string (nullable = true)
 |-- end_station_name: string (nullable = true)
 |-- end_station_id: string (nullable = true)
 |-- start_lat: double (nullable = true)
 |-- start_lng: double (nullable = true)
 |-- end_lat: double (nullable = true)
 |-- end_lng: double (nullable = true)
 |-- member_casual: string (nullable = true)

In [38]:
lazy_df1.collect()

shape: (999, 13)
┌────────────┬────────────┬────────────┬───────────┬───┬───────────┬─────────┬─────────┬───────────┐
│ ride_id    ┆ rideable_t ┆ started_at ┆ ended_at  ┆ … ┆ start_lng ┆ end_lat ┆ end_lng ┆ member_ca │
│ ---        ┆ ype        ┆ ---        ┆ ---       ┆   ┆ ---       ┆ ---     ┆ ---     ┆ sual      │
│ str        ┆ ---        ┆ str        ┆ str       ┆   ┆ f64       ┆ f64     ┆ f64     ┆ ---       │
│            ┆ str        ┆            ┆           ┆   ┆           ┆         ┆         ┆ str       │
╞════════════╪════════════╪════════════╪═══════════╪═══╪═══════════╪═════════╪═════════╪═══════════╡
│ 6F1682AC40 ┆ electric_b ┆ 2023-06-05 ┆ 2023-06-0 ┆ … ┆ -87.69    ┆ 41.91   ┆ -87.7   ┆ member    │
│ EB6F71     ┆ ike        ┆ 13:34:12   ┆ 5         ┆   ┆           ┆         ┆         ┆           │
│            ┆            ┆            ┆ 14:31:56  ┆   ┆           ┆         ┆         ┆           │
│ 622A1686D6 ┆ electric_b ┆ 2023-06-05 ┆ 2023-06-0 ┆ … ┆ -87.65    ┆ 41.94   ┆ -87.65  ┆ member    │
│ 4948EB     ┆ ike        ┆ 01:30:22   ┆ 5         ┆   ┆           ┆         ┆         ┆           │
│            ┆            ┆            ┆ 01:33:06  ┆   ┆           ┆         ┆         ┆           │
│ 3C88859D92 ┆ electric_b ┆ 2023-06-20 ┆ 2023-06-2 ┆ … ┆ -87.68    ┆ 41.92   ┆ -87.63  ┆ member    │
│ 6253B4     ┆ ike        ┆ 18:15:49   ┆ 0         ┆   ┆           ┆         ┆         ┆           │
│            ┆            ┆            ┆ 18:32:05  ┆   ┆           ┆         ┆         ┆           │
│ EAD8A5E025 ┆ electric_b ┆ 2023-06-19 ┆ 2023-06-1 ┆ … ┆ -87.65    ┆ 41.98   ┆ -87.66  ┆ member    │
│ 9DEC88     ┆ ike        ┆ 14:56:00   ┆ 9         ┆   ┆           ┆         ┆         ┆           │
│            ┆            ┆            ┆ 15:00:35  ┆   ┆           ┆         ┆         ┆           │
│ 5A36F21930 ┆ electric_b ┆ 2023-06-19 ┆ 2023-06-1 ┆ … ┆ -87.66    ┆ 41.99   ┆ -87.65  ┆ member    │
│ D6A55C     ┆ ike        ┆ 15:03:34   ┆ 9         ┆   ┆           ┆         ┆         ┆           │
│            ┆            ┆            ┆ 15:07:16  ┆   ┆           ┆         ┆         ┆           │
│ …          ┆ …          ┆ …          ┆ …         ┆ … ┆ …         ┆ …       ┆ …       ┆ …         │
│ 3B780A995A ┆ electric_b ┆ 2023-06-18 ┆ 2023-06-1 ┆ … ┆ -87.72    ┆ 41.97   ┆ -87.73  ┆ member    │
│ 0219E3     ┆ ike        ┆ 08:32:16   ┆ 8         ┆   ┆           ┆         ┆         ┆           │
│            ┆            ┆            ┆ 08:39:34  ┆   ┆           ┆         ┆         ┆           │
│ 73EAB52DC6 ┆ electric_b ┆ 2023-06-18 ┆ 2023-06-1 ┆ … ┆ -87.67    ┆ 41.92   ┆ -87.68  ┆ member    │
│ 92D9A1     ┆ ike        ┆ 01:07:38   ┆ 8         ┆   ┆           ┆         ┆         ┆           │
│            ┆            ┆            ┆ 01:14:07  ┆   ┆           ┆         ┆         ┆           │
│ EAC18E1F19 ┆ electric_b ┆ 2023-06-17 ┆ 2023-06-1 ┆ … ┆ -87.68    ┆ 41.92   ┆ -87.68  ┆ member    │
│ E5A05B     ┆ ike        ┆ 20:24:58   ┆ 7         ┆   ┆           ┆         ┆         ┆           │
│            ┆            ┆            ┆ 20:25:08  ┆   ┆           ┆         ┆         ┆           │
│ DB04F0278D ┆ electric_b ┆ 2023-06-18 ┆ 2023-06-1 ┆ … ┆ -87.69716 ┆ 41.9    ┆ -87.66  ┆ member    │
│ 4E085B     ┆ ike        ┆ 17:47:30   ┆ 8         ┆   ┆           ┆         ┆         ┆           │
│            ┆            ┆            ┆ 18:01:14  ┆   ┆           ┆         ┆         ┆           │
│ E113CD59DB ┆ electric_b ┆ 2023-06-29 ┆ 2023-06-2 ┆ … ┆ -87.66    ┆ 41.95   ┆ -87.66  ┆ member    │
│ 0D940A     ┆ ike        ┆ 10:24:37   ┆ 9         ┆   ┆           ┆         ┆         ┆           │
│            ┆            ┆            ┆ 10:30:05  ┆   ┆           ┆         ┆         ┆           │
└────────────┴────────────┴────────────┴───────────┴───┴───────────┴─────────┴─────────┴───────────┘

In [60]:
schema_overrides = {
    "ride_id": pl.Categorical,
    "rideable_type": pl.String,
    "started_at": pl.Datetime,
    "ended_at":pl.Datetime,
    "start_station_name":pl.String,
    "start_station_id":pl.String,
    "end_station_name":pl.String,
    "end_station_id":pl.String,
    "start_lat":pl.Float64,
    "start_lng":pl.Float64,
    "end_lat":pl.Float64,
    "end_lng":pl.Float64,
    "member_casual":pl.String
}

lazy_df = pl.scan_csv("data/202306-divvy-tripdata.csv", schema_overrides=schema_overrides)
lazy_df.collect()

shape: (999, 13)
┌────────────┬────────────┬────────────┬───────────┬───┬───────────┬─────────┬─────────┬───────────┐
│ ride_id    ┆ rideable_t ┆ started_at ┆ ended_at  ┆ … ┆ start_lng ┆ end_lat ┆ end_lng ┆ member_ca │
│ ---        ┆ ype        ┆ ---        ┆ ---       ┆   ┆ ---       ┆ ---     ┆ ---     ┆ sual      │
│ cat        ┆ ---        ┆ datetime[μ ┆ datetime[ ┆   ┆ f64       ┆ f64     ┆ f64     ┆ ---       │
│            ┆ str        ┆ s]         ┆ μs]       ┆   ┆           ┆         ┆         ┆ str       │
╞════════════╪════════════╪════════════╪═══════════╪═══╪═══════════╪═════════╪═════════╪═══════════╡
│ 6F1682AC40 ┆ electric_b ┆ 2023-06-05 ┆ 2023-06-0 ┆ … ┆ -87.69    ┆ 41.91   ┆ -87.7   ┆ member    │
│ EB6F71     ┆ ike        ┆ 13:34:12   ┆ 5         ┆   ┆           ┆         ┆         ┆           │
│            ┆            ┆            ┆ 14:31:56  ┆   ┆           ┆         ┆         ┆           │
│ 622A1686D6 ┆ electric_b ┆ 2023-06-05 ┆ 2023-06-0 ┆ … ┆ -87.65    ┆ 41.94   ┆ -87.65  ┆ member    │
│ 4948EB     ┆ ike        ┆ 01:30:22   ┆ 5         ┆   ┆           ┆         ┆         ┆           │
│            ┆            ┆            ┆ 01:33:06  ┆   ┆           ┆         ┆         ┆           │
│ 3C88859D92 ┆ electric_b ┆ 2023-06-20 ┆ 2023-06-2 ┆ … ┆ -87.68    ┆ 41.92   ┆ -87.63  ┆ member    │
│ 6253B4     ┆ ike        ┆ 18:15:49   ┆ 0         ┆   ┆           ┆         ┆         ┆           │
│            ┆            ┆            ┆ 18:32:05  ┆   ┆           ┆         ┆         ┆           │
│ EAD8A5E025 ┆ electric_b ┆ 2023-06-19 ┆ 2023-06-1 ┆ … ┆ -87.65    ┆ 41.98   ┆ -87.66  ┆ member    │
│ 9DEC88     ┆ ike        ┆ 14:56:00   ┆ 9         ┆   ┆           ┆         ┆         ┆           │
│            ┆            ┆            ┆ 15:00:35  ┆   ┆           ┆         ┆         ┆           │
│ 5A36F21930 ┆ electric_b ┆ 2023-06-19 ┆ 2023-06-1 ┆ … ┆ -87.66    ┆ 41.99   ┆ -87.65  ┆ member    │
│ D6A55C     ┆ ike        ┆ 15:03:34   ┆ 9         ┆   ┆           ┆         ┆         ┆           │
│            ┆            ┆            ┆ 15:07:16  ┆   ┆           ┆         ┆         ┆           │
│ …          ┆ …          ┆ …          ┆ …         ┆ … ┆ …         ┆ …       ┆ …       ┆ …         │
│ 3B780A995A ┆ electric_b ┆ 2023-06-18 ┆ 2023-06-1 ┆ … ┆ -87.72    ┆ 41.97   ┆ -87.73  ┆ member    │
│ 0219E3     ┆ ike        ┆ 08:32:16   ┆ 8         ┆   ┆           ┆         ┆         ┆           │
│            ┆            ┆            ┆ 08:39:34  ┆   ┆           ┆         ┆         ┆           │
│ 73EAB52DC6 ┆ electric_b ┆ 2023-06-18 ┆ 2023-06-1 ┆ … ┆ -87.67    ┆ 41.92   ┆ -87.68  ┆ member    │
│ 92D9A1     ┆ ike        ┆ 01:07:38   ┆ 8         ┆   ┆           ┆         ┆         ┆           │
│            ┆            ┆            ┆ 01:14:07  ┆   ┆           ┆         ┆         ┆           │
│ EAC18E1F19 ┆ electric_b ┆ 2023-06-17 ┆ 2023-06-1 ┆ … ┆ -87.68    ┆ 41.92   ┆ -87.68  ┆ member    │
│ E5A05B     ┆ ike        ┆ 20:24:58   ┆ 7         ┆   ┆           ┆         ┆         ┆           │
│            ┆            ┆            ┆ 20:25:08  ┆   ┆           ┆         ┆         ┆           │
│ DB04F0278D ┆ electric_b ┆ 2023-06-18 ┆ 2023-06-1 ┆ … ┆ -87.69716 ┆ 41.9    ┆ -87.66  ┆ member    │
│ 4E085B     ┆ ike        ┆ 17:47:30   ┆ 8         ┆   ┆           ┆         ┆         ┆           │
│            ┆            ┆            ┆ 18:01:14  ┆   ┆           ┆         ┆         ┆           │
│ E113CD59DB ┆ electric_b ┆ 2023-06-29 ┆ 2023-06-2 ┆ … ┆ -87.66    ┆ 41.95   ┆ -87.66  ┆ member    │
│ 0D940A     ┆ ike        ┆ 10:24:37   ┆ 9         ┆   ┆           ┆         ┆         ┆           │
│            ┆            ┆            ┆ 10:30:05  ┆   ┆           ┆         ┆         ┆           │
└────────────┴────────────┴────────────┴───────────┴───┴───────────┴─────────┴─────────┴───────────┘

In [64]:
# Q1. Convert all data types to the correct ones.
schema_overrides = {
    "ride_id": pl.Categorical,
    "rideable_type": pl.String,
    "started_at": pl.Datetime,
    "ended_at":pl.Datetime,
    "start_station_name":pl.String,
    "start_station_id":pl.String,
    "end_station_name":pl.String,
    "end_station_id":pl.String,
    "start_lat":pl.Float64,
    "start_lng":pl.Float64,
    "end_lat":pl.Float64,
    "end_lng":pl.Float64,
    "member_casual":pl.String
}

lazy_df = pl.scan_csv("data/202306-divvy-tripdata.csv", schema_overrides=schema_overrides)
lazy_df.collect()

shape: (999, 13)
┌────────────┬────────────┬────────────┬───────────┬───┬───────────┬─────────┬─────────┬───────────┐
│ ride_id    ┆ rideable_t ┆ started_at ┆ ended_at  ┆ … ┆ start_lng ┆ end_lat ┆ end_lng ┆ member_ca │
│ ---        ┆ ype        ┆ ---        ┆ ---       ┆   ┆ ---       ┆ ---     ┆ ---     ┆ sual      │
│ cat        ┆ ---        ┆ datetime[μ ┆ datetime[ ┆   ┆ f64       ┆ f64     ┆ f64     ┆ ---       │
│            ┆ str        ┆ s]         ┆ μs]       ┆   ┆           ┆         ┆         ┆ str       │
╞════════════╪════════════╪════════════╪═══════════╪═══╪═══════════╪═════════╪═════════╪═══════════╡
│ 6F1682AC40 ┆ electric_b ┆ 2023-06-05 ┆ 2023-06-0 ┆ … ┆ -87.69    ┆ 41.91   ┆ -87.7   ┆ member    │
│ EB6F71     ┆ ike        ┆ 13:34:12   ┆ 5         ┆   ┆           ┆         ┆         ┆           │
│            ┆            ┆            ┆ 14:31:56  ┆   ┆           ┆         ┆         ┆           │
│ 622A1686D6 ┆ electric_b ┆ 2023-06-05 ┆ 2023-06-0 ┆ … ┆ -87.65    ┆ 41.94   ┆ -87.65  ┆ member    │
│ 4948EB     ┆ ike        ┆ 01:30:22   ┆ 5         ┆   ┆           ┆         ┆         ┆           │
│            ┆            ┆            ┆ 01:33:06  ┆   ┆           ┆         ┆         ┆           │
│ 3C88859D92 ┆ electric_b ┆ 2023-06-20 ┆ 2023-06-2 ┆ … ┆ -87.68    ┆ 41.92   ┆ -87.63  ┆ member    │
│ 6253B4     ┆ ike        ┆ 18:15:49   ┆ 0         ┆   ┆           ┆         ┆         ┆           │
│            ┆            ┆            ┆ 18:32:05  ┆   ┆           ┆         ┆         ┆           │
│ EAD8A5E025 ┆ electric_b ┆ 2023-06-19 ┆ 2023-06-1 ┆ … ┆ -87.65    ┆ 41.98   ┆ -87.66  ┆ member    │
│ 9DEC88     ┆ ike        ┆ 14:56:00   ┆ 9         ┆   ┆           ┆         ┆         ┆           │
│            ┆            ┆            ┆ 15:00:35  ┆   ┆           ┆         ┆         ┆           │
│ 5A36F21930 ┆ electric_b ┆ 2023-06-19 ┆ 2023-06-1 ┆ … ┆ -87.66    ┆ 41.99   ┆ -87.65  ┆ member    │
│ D6A55C     ┆ ike        ┆ 15:03:34   ┆ 9         ┆   ┆           ┆         ┆         ┆           │
│            ┆            ┆            ┆ 15:07:16  ┆   ┆           ┆         ┆         ┆           │
│ …          ┆ …          ┆ …          ┆ …         ┆ … ┆ …         ┆ …       ┆ …       ┆ …         │
│ 3B780A995A ┆ electric_b ┆ 2023-06-18 ┆ 2023-06-1 ┆ … ┆ -87.72    ┆ 41.97   ┆ -87.73  ┆ member    │
│ 0219E3     ┆ ike        ┆ 08:32:16   ┆ 8         ┆   ┆           ┆         ┆         ┆           │
│            ┆            ┆            ┆ 08:39:34  ┆   ┆           ┆         ┆         ┆           │
│ 73EAB52DC6 ┆ electric_b ┆ 2023-06-18 ┆ 2023-06-1 ┆ … ┆ -87.67    ┆ 41.92   ┆ -87.68  ┆ member    │
│ 92D9A1     ┆ ike        ┆ 01:07:38   ┆ 8         ┆   ┆           ┆         ┆         ┆           │
│            ┆            ┆            ┆ 01:14:07  ┆   ┆           ┆         ┆         ┆           │
│ EAC18E1F19 ┆ electric_b ┆ 2023-06-17 ┆ 2023-06-1 ┆ … ┆ -87.68    ┆ 41.92   ┆ -87.68  ┆ member    │
│ E5A05B     ┆ ike        ┆ 20:24:58   ┆ 7         ┆   ┆           ┆         ┆         ┆           │
│            ┆            ┆            ┆ 20:25:08  ┆   ┆           ┆         ┆         ┆           │
│ DB04F0278D ┆ electric_b ┆ 2023-06-18 ┆ 2023-06-1 ┆ … ┆ -87.69716 ┆ 41.9    ┆ -87.66  ┆ member    │
│ 4E085B     ┆ ike        ┆ 17:47:30   ┆ 8         ┆   ┆           ┆         ┆         ┆           │
│            ┆            ┆            ┆ 18:01:14  ┆   ┆           ┆         ┆         ┆           │
│ E113CD59DB ┆ electric_b ┆ 2023-06-29 ┆ 2023-06-2 ┆ … ┆ -87.66    ┆ 41.95   ┆ -87.66  ┆ member    │
│ 0D940A     ┆ ike        ┆ 10:24:37   ┆ 9         ┆   ┆           ┆         ┆         ┆           │
│            ┆            ┆            ┆ 10:30:05  ┆   ┆           ┆         ┆         ┆           │
└────────────┴────────────┴────────────┴───────────┴───┴───────────┴─────────┴─────────┴───────────┘

In [80]:
# Q2. Count the number bike rides per day.
lazy_df.select("started_at").unique().collect()
lazy_df = lazy_df.with_columns(pl.col("started_at").dt.date().alias("Started_date"))
result = lazy_df.select("Started_date").group_by("Started_date").count().collect()
result.write_csv("Results/Total_Rides_Per_day.csv",include_header=True)
results

There are 30 unique Dtaes

/tmp/ipykernel_23618/3088121390.py:4: DeprecationWarning: `count` was renamed; use `len` instead
  result = lazy_df.select("Started_date").group_by("Started_date").count().collect()

In [67]:
lazy_df = lazy_df.with_columns(pl.col("started_at").dt.date().alias("Started_date"))

In [76]:
result = lazy_df.select("Started_date").group_by("Started_date").count().collect()
result.write_csv("Results/Total_Rides_Per_day.csv",include_header=True)
print("There are {} unique Dates".format(result.shape[0]))

There are 30 unique Dtaes

/tmp/ipykernel_23618/1615587515.py:1: DeprecationWarning: `count` was renamed; use `len` instead
  result = lazy_df.select("Started_date").group_by("Started_date").count().collect()

In [81]:
result

shape: (30, 2)
┌──────────────┬───────┐
│ Started_date ┆ count │
│ ---          ┆ ---   │
│ date         ┆ u32   │
╞══════════════╪═══════╡
│ 2023-06-20   ┆ 28    │
│ 2023-06-22   ┆ 53    │
│ 2023-06-05   ┆ 31    │
│ 2023-06-17   ┆ 37    │
│ 2023-06-06   ┆ 22    │
│ …            ┆ …     │
│ 2023-06-08   ┆ 16    │
│ 2023-06-28   ┆ 35    │
│ 2023-06-03   ┆ 33    │
│ 2023-06-09   ┆ 45    │
│ 2023-06-29   ┆ 26    │
└──────────────┴───────┘

In [86]:
lazy_df.columns

/tmp/ipykernel_23618/4236129083.py:1: PerformanceWarning: Determining the column names of a LazyFrame requires resolving its schema, which is a potentially expensive operation. Use `LazyFrame.collect_schema().names()` to get the column names without this warning.
  lazy_df.columns

['ride_id',
 'rideable_type',
 'started_at',
 'ended_at',
 'start_station_name',
 'start_station_id',
 'end_station_name',
 'end_station_id',
 'start_lat',
 'start_lng',
 'end_lat',
 'end_lng',
 'member_casual',
 'Started_date']

In [87]:
# Q3. Calculate the average, max, and minimum number of rides per week of the dataset.
ldf = lazy_df.with_columns(pl.col("Started_date").dt.week().alias("week"))

In [90]:
ldf.collect()

shape: (999, 15)
┌────────────┬────────────┬────────────┬────────────┬───┬─────────┬────────────┬────────────┬──────┐
│ ride_id    ┆ rideable_t ┆ started_at ┆ ended_at   ┆ … ┆ end_lng ┆ member_cas ┆ Started_da ┆ week │
│ ---        ┆ ype        ┆ ---        ┆ ---        ┆   ┆ ---     ┆ ual        ┆ te         ┆ ---  │
│ cat        ┆ ---        ┆ datetime[μ ┆ datetime[μ ┆   ┆ f64     ┆ ---        ┆ ---        ┆ i8   │
│            ┆ str        ┆ s]         ┆ s]         ┆   ┆         ┆ str        ┆ date       ┆      │
╞════════════╪════════════╪════════════╪════════════╪═══╪═════════╪════════════╪════════════╪══════╡
│ 6F1682AC40 ┆ electric_b ┆ 2023-06-05 ┆ 2023-06-05 ┆ … ┆ -87.7   ┆ member     ┆ 2023-06-05 ┆ 23   │
│ EB6F71     ┆ ike        ┆ 13:34:12   ┆ 14:31:56   ┆   ┆         ┆            ┆            ┆      │
│ 622A1686D6 ┆ electric_b ┆ 2023-06-05 ┆ 2023-06-05 ┆ … ┆ -87.65  ┆ member     ┆ 2023-06-05 ┆ 23   │
│ 4948EB     ┆ ike        ┆ 01:30:22   ┆ 01:33:06   ┆   ┆         ┆            ┆            ┆      │
│ 3C88859D92 ┆ electric_b ┆ 2023-06-20 ┆ 2023-06-20 ┆ … ┆ -87.63  ┆ member     ┆ 2023-06-20 ┆ 25   │
│ 6253B4     ┆ ike        ┆ 18:15:49   ┆ 18:32:05   ┆   ┆         ┆            ┆            ┆      │
│ EAD8A5E025 ┆ electric_b ┆ 2023-06-19 ┆ 2023-06-19 ┆ … ┆ -87.66  ┆ member     ┆ 2023-06-19 ┆ 25   │
│ 9DEC88     ┆ ike        ┆ 14:56:00   ┆ 15:00:35   ┆   ┆         ┆            ┆            ┆      │
│ 5A36F21930 ┆ electric_b ┆ 2023-06-19 ┆ 2023-06-19 ┆ … ┆ -87.65  ┆ member     ┆ 2023-06-19 ┆ 25   │
│ D6A55C     ┆ ike        ┆ 15:03:34   ┆ 15:07:16   ┆   ┆         ┆            ┆            ┆      │
│ …          ┆ …          ┆ …          ┆ …          ┆ … ┆ …       ┆ …          ┆ …          ┆ …    │
│ 3B780A995A ┆ electric_b ┆ 2023-06-18 ┆ 2023-06-18 ┆ … ┆ -87.73  ┆ member     ┆ 2023-06-18 ┆ 24   │
│ 0219E3     ┆ ike        ┆ 08:32:16   ┆ 08:39:34   ┆   ┆         ┆            ┆            ┆      │
│ 73EAB52DC6 ┆ electric_b ┆ 2023-06-18 ┆ 2023-06-18 ┆ … ┆ -87.68  ┆ member     ┆ 2023-06-18 ┆ 24   │
│ 92D9A1     ┆ ike        ┆ 01:07:38   ┆ 01:14:07   ┆   ┆         ┆            ┆            ┆      │
│ EAC18E1F19 ┆ electric_b ┆ 2023-06-17 ┆ 2023-06-17 ┆ … ┆ -87.68  ┆ member     ┆ 2023-06-17 ┆ 24   │
│ E5A05B     ┆ ike        ┆ 20:24:58   ┆ 20:25:08   ┆   ┆         ┆            ┆            ┆      │
│ DB04F0278D ┆ electric_b ┆ 2023-06-18 ┆ 2023-06-18 ┆ … ┆ -87.66  ┆ member     ┆ 2023-06-18 ┆ 24   │
│ 4E085B     ┆ ike        ┆ 17:47:30   ┆ 18:01:14   ┆   ┆         ┆            ┆            ┆      │
│ E113CD59DB ┆ electric_b ┆ 2023-06-29 ┆ 2023-06-29 ┆ … ┆ -87.66  ┆ member     ┆ 2023-06-29 ┆ 26   │
│ 0D940A     ┆ ike        ┆ 10:24:37   ┆ 10:30:05   ┆   ┆         ┆            ┆            ┆      │
└────────────┴────────────┴────────────┴────────────┴───┴─────────┴────────────┴────────────┴──────┘

In [105]:
# Q3. Calculate the average, max, and minimum number of rides per week of the dataset.
ldf = lazy_df.with_columns(pl.col("Started_date").dt.week().alias("week"))
res =  ldf.group_by("week").agg([pl.count("ride_id").alias("Ride_Count")])\
.select(
    [pl.mean("Ride_Count").alias("Average_Rides"), 
     pl.max("Ride_Count").alias("Max_rides"), 
     pl.min("Ride_Count").alias("Min_rides")]).collect()

res.write_csv("Results/average_max_minimum_number_of_rides_per_week.csv", include_header=True)
res

shape: (1, 3)
┌───────────────┬───────────┬───────────┐
│ Average_Rides ┆ Max_rides ┆ Min_rides │
│ ---           ┆ ---       ┆ ---       │
│ f64           ┆ u32       ┆ u32       │
╞═══════════════╪═══════════╪═══════════╡
│ 199.8         ┆ 286       ┆ 142       │
└───────────────┴───────────┴───────────┘

In [111]:
# Q4. For each day, calculate how many rides that day is above or below the same day last week.
f_df = ldf.filter(pl.col("week")>23).dt
f_df.collect()

TypeError: "'>'" comparison not supported for LazyFrame objects

In [129]:
# Ensure date column is sorted
df = ldf.sort("Started_date")

# Count rides per day
daily_counts = (
    df.group_by("Started_date")
      .agg(pl.count("ride_id").alias("ride_count"))
)

# Add day-of-week and previous week's date
daily_counts = daily_counts.with_columns([
    pl.col("Started_date").dt.weekday().alias("day_of_week"),
    (pl.col("Started_date") - pl.duration(days=7)).alias("last_week_date")
])

result = daily_counts.join(
    daily_counts.select(pl.col("Started_date").alias("last_week_date"), pl.col("ride_count").alias("last_week_ride_count")),
    on="last_week_date",
    how="left"
).with_columns([
    (pl.col("ride_count").cast(pl.Int32) - pl.col("last_week_ride_count").cast(pl.Int32)).alias("diff_vs_last_week")
])   

# Select final columns
result = result.select("Started_date", "day_of_week", "ride_count", "last_week_ride_count", "diff_vs_last_week").collect()
result.write_csv("Results/Diff_b_w_current_and_last_weeks_day.csv", include_header=True)
result

shape: (30, 5)
┌──────────────┬─────────────┬────────────┬──────────────────────┬───────────────────┐
│ Started_date ┆ day_of_week ┆ ride_count ┆ last_week_ride_count ┆ diff_vs_last_week │
│ ---          ┆ ---         ┆ ---        ┆ ---                  ┆ ---               │
│ date         ┆ i8          ┆ u32        ┆ u32                  ┆ i32               │
╞══════════════╪═════════════╪════════════╪══════════════════════╪═══════════════════╡
│ 2023-06-07   ┆ 3           ┆ 33         ┆ null                 ┆ null              │
│ 2023-06-26   ┆ 1           ┆ 21         ┆ 58                   ┆ -37               │
│ 2023-06-27   ┆ 2           ┆ 20         ┆ 28                   ┆ -8                │
│ 2023-06-30   ┆ 5           ┆ 51         ┆ 45                   ┆ 6                 │
│ 2023-06-15   ┆ 4           ┆ 24         ┆ 16                   ┆ 8                 │
│ …            ┆ …           ┆ …          ┆ …                    ┆ …                 │
│ 2023-06-23   ┆ 5           ┆ 45         ┆ 33                   ┆ 12                │
│ 2023-06-18   ┆ 7           ┆ 29         ┆ 13                   ┆ 16                │
│ 2023-06-02   ┆ 5           ┆ 40         ┆ null                 ┆ null              │
│ 2023-06-04   ┆ 7           ┆ 26         ┆ null                 ┆ null              │
│ 2023-06-16   ┆ 5           ┆ 33         ┆ 45                   ┆ -12               │
└──────────────┴─────────────┴────────────┴──────────────────────┴───────────────────┘

In [132]:
import polars as pl


def main():

    # Q1. Convert all data types to the correct ones.
    def dtypes_ckecking_and_updating():
        schema_overrides = {
        "ride_id": pl.Categorical,
        "rideable_type": pl.String,
        "started_at": pl.Datetime,
        "ended_at":pl.Datetime,
        "start_station_name":pl.String,
        "start_station_id":pl.String,
        "end_station_name":pl.String,
        "end_station_id":pl.String,
        "start_lat":pl.Float64,
        "start_lng":pl.Float64,
        "end_lat":pl.Float64,
        "end_lng":pl.Float64,
        "member_casual":pl.String
        }

        lazy_df = pl.scan_csv("data/202306-divvy-tripdata.csv", schema_overrides=schema_overrides)
        print(lazy_df.limit(10).collect())
        return lazy_df
    
    # Q2. Count the number bike rides per day.
    def count_number_of_bike_rides_perDay():
        lazy_df.select("started_at").unique().collect()
        lazy_df = lazy_df.with_columns(pl.col("started_at").dt.date().alias("Started_date"))
        result = lazy_df.select("Started_date").group_by("Started_date").count().collect()
        result.write_csv("Results/Total_Rides_Per_day.csv",include_header=True)
        return results
    
    # Q3. Calculate the average, max, and minimum number of rides per week of the dataset.
    def avg_max_min_number_of_rides_per_week():
        ldf = lazy_df.with_columns(pl.col("Started_date").dt.week().alias("week"))
        res =  ldf.group_by("week").agg([pl.count("ride_id").alias("Ride_Count")])\
        .select(
            [pl.mean("Ride_Count").alias("Average_Rides"), 
             pl.max("Ride_Count").alias("Max_rides"), 
             pl.min("Ride_Count").alias("Min_rides")]).collect()

        res.write_csv("Results/average_max_minimum_number_of_rides_per_week.csv", include_header=True)
        return res

    
    # Q4. For each day, calculate how many rides that day is above or below the same day last week.
    def diff_b_w_days_of_ride():
        df = lazy_df.sort("Started_date")
        
        # Count rides per day
        daily_counts = (
            df.group_by("Started_date")
              .agg(pl.count("ride_id").alias("ride_count"))
        )
        
        # Add day-of-week and previous week's date
        daily_counts = daily_counts.with_columns([
            pl.col("Started_date").dt.weekday().alias("day_of_week"),
            (pl.col("Started_date") - pl.duration(days=7)).alias("last_week_date")
        ])
        
        result = daily_counts.join(
            daily_counts.select(pl.col("Started_date").alias("last_week_date"), pl.col("ride_count").alias("last_week_ride_count")),
            on="last_week_date",
            how="left"
        ).with_columns([
            (pl.col("ride_count").cast(pl.Int32) - pl.col("last_week_ride_count").cast(pl.Int32)).alias("diff_vs_last_week")
        ])   
        
        # Select final columns
        result = result.select("Started_date", "day_of_week", "ride_count", "last_week_ride_count", "diff_vs_last_week").collect()
        result.write_csv("Results/Diff_b_w_current_and_last_weeks_day.csv", include_header=True)
        return result


    a = dtypes_ckecking_and_updating()
    b = count_number_of_bike_rides_perDay(lazy_df)
    c = avg_max_min_number_of_rides_per_week(lazy_df)
    d = diff_b_w_days_of_ride(lazy_df)


if __name__ == "__main__":
    main()

shape: (10, 13)
┌────────────┬────────────┬────────────┬───────────┬───┬───────────┬─────────┬─────────┬───────────┐
│ ride_id    ┆ rideable_t ┆ started_at ┆ ended_at  ┆ … ┆ start_lng ┆ end_lat ┆ end_lng ┆ member_ca │
│ ---        ┆ ype        ┆ ---        ┆ ---       ┆   ┆ ---       ┆ ---     ┆ ---     ┆ sual      │
│ cat        ┆ ---        ┆ datetime[μ ┆ datetime[ ┆   ┆ f64       ┆ f64     ┆ f64     ┆ ---       │
│            ┆ str        ┆ s]         ┆ μs]       ┆   ┆           ┆         ┆         ┆ str       │
╞════════════╪════════════╪════════════╪═══════════╪═══╪═══════════╪═════════╪═════════╪═══════════╡
│ 6F1682AC40 ┆ electric_b ┆ 2023-06-05 ┆ 2023-06-0 ┆ … ┆ -87.69    ┆ 41.91   ┆ -87.7   ┆ member    │
│ EB6F71     ┆ ike        ┆ 13:34:12   ┆ 5         ┆   ┆           ┆         ┆         ┆           │
│            ┆            ┆            ┆ 14:31:56  ┆   ┆           ┆         ┆         ┆           │
│ 622A1686D6 ┆ electric_b ┆ 2023-06-05 ┆ 2023-06-0 ┆ … ┆ -87.65    ┆ 41.94   ┆ -87.65  ┆ member    │
│ 4948EB     ┆ ike        ┆ 01:30:22   ┆ 5         ┆   ┆           ┆         ┆         ┆           │
│            ┆            ┆            ┆ 01:33:06  ┆   ┆           ┆         ┆         ┆           │
│ 3C88859D92 ┆ electric_b ┆ 2023-06-20 ┆ 2023-06-2 ┆ … ┆ -87.68    ┆ 41.92   ┆ -87.63  ┆ member    │
│ 6253B4     ┆ ike        ┆ 18:15:49   ┆ 0         ┆   ┆           ┆         ┆         ┆           │
│            ┆            ┆            ┆ 18:32:05  ┆   ┆           ┆         ┆         ┆           │
│ EAD8A5E025 ┆ electric_b ┆ 2023-06-19 ┆ 2023-06-1 ┆ … ┆ -87.65    ┆ 41.98   ┆ -87.66  ┆ member    │
│ 9DEC88     ┆ ike        ┆ 14:56:00   ┆ 9         ┆   ┆           ┆         ┆         ┆           │
│            ┆            ┆            ┆ 15:00:35  ┆   ┆           ┆         ┆         ┆           │
│ 5A36F21930 ┆ electric_b ┆ 2023-06-19 ┆ 2023-06-1 ┆ … ┆ -87.66    ┆ 41.99   ┆ -87.65  ┆ member    │
│ D6A55C     ┆ ike        ┆ 15:03:34   ┆ 9         ┆   ┆           ┆         ┆         ┆           │
│            ┆            ┆            ┆ 15:07:16  ┆   ┆           ┆         ┆         ┆           │
│ CF682EA7D0 ┆ electric_b ┆ 2023-06-09 ┆ 2023-06-0 ┆ … ┆ -87.68    ┆ 41.94   ┆ -87.65  ┆ member    │
│ F961DB     ┆ ike        ┆ 21:30:25   ┆ 9         ┆   ┆           ┆         ┆         ┆           │
│            ┆            ┆            ┆ 21:49:52  ┆   ┆           ┆         ┆         ┆           │
│ 4910FBB710 ┆ electric_b ┆ 2023-06-03 ┆ 2023-06-0 ┆ … ┆ -87.62    ┆ 41.88   ┆ -87.62  ┆ member    │
│ 157754     ┆ ike        ┆ 13:34:09   ┆ 3         ┆   ┆           ┆         ┆         ┆           │
│            ┆            ┆            ┆ 13:34:28  ┆   ┆           ┆         ┆         ┆           │
│ EA19D850A4 ┆ electric_b ┆ 2023-06-03 ┆ 2023-06-0 ┆ … ┆ -87.62    ┆ 41.88   ┆ -87.62  ┆ member    │
│ 2F56D8     ┆ ike        ┆ 13:34:46   ┆ 3         ┆   ┆           ┆         ┆         ┆           │
│            ┆            ┆            ┆ 13:35:00  ┆   ┆           ┆         ┆         ┆           │
│ E68F437846 ┆ electric_b ┆ 2023-06-02 ┆ 2023-06-0 ┆ … ┆ -87.64    ┆ 41.95   ┆ -87.65  ┆ member    │
│ 62A2D0     ┆ ike        ┆ 22:27:35   ┆ 2         ┆   ┆           ┆         ┆         ┆           │
│            ┆            ┆            ┆ 22:35:26  ┆   ┆           ┆         ┆         ┆           │
│ 5A013E29CC ┆ electric_b ┆ 2023-06-02 ┆ 2023-06-0 ┆ … ┆ -87.63    ┆ 41.89   ┆ -87.63  ┆ member    │
│ 001611     ┆ ike        ┆ 21:18:31   ┆ 3         ┆   ┆           ┆         ┆         ┆           │
│            ┆            ┆            ┆ 01:27:19  ┆   ┆           ┆         ┆         ┆           │
└────────────┴────────────┴────────────┴───────────┴───┴───────────┴─────────┴─────────┴───────────┘

TypeError: main.<locals>.count_number_of_bike_rides_perDay() takes 0 positional arguments but 1 was given

In [137]:
import polars as pl


def main():
    # Q1. Convert all data types to the correct ones.
    def dtypes_checking_and_updating():
        schema_overrides = {
            "ride_id": pl.Categorical,
            "rideable_type": pl.String,
            "started_at": pl.Datetime,
            "ended_at": pl.Datetime,
            "start_station_name": pl.String,
            "start_station_id": pl.String,
            "end_station_name": pl.String,
            "end_station_id": pl.String,
            "start_lat": pl.Float64,
            "start_lng": pl.Float64,
            "end_lat": pl.Float64,
            "end_lng": pl.Float64,
            "member_casual": pl.String,
        }
        return pl.scan_csv("data/202306-divvy-tripdata.csv", schema_overrides=schema_overrides)

    # Q2. Count the number of bike rides per day.
    def count_number_of_bike_rides_per_day(lazy_df):
        df = lazy_df.with_columns(pl.col("started_at").dt.date().alias("Started_date"))
        result = (df.group_by("Started_date").agg(pl.len().alias("count")).collect())
        result.write_csv("Results/Total_Rides_Per_day.csv", include_header=True)
        return result

    # Q3. Calculate average, max, and min number of rides per week.
    def avg_max_min_number_of_rides_per_week(lazy_df):
        df = lazy_df.with_columns(pl.col("started_at").dt.date().alias("Started_date"))
        df = df.with_columns(pl.col("Started_date").dt.week().alias("week"))
        res = (
            df.group_by("week")
            .agg(pl.len().alias("Ride_Count"))
            .select([
                pl.mean("Ride_Count").alias("Average_Rides"),
                pl.max("Ride_Count").alias("Max_rides"),
                pl.min("Ride_Count").alias("Min_rides")
            ])
            .collect()
        )
        res.write_csv("Results/average_max_minimum_number_of_rides_per_week.csv", include_header=True)
        return res

    # Q4. For each day, calculate how many rides above/below same day last week.
    def diff_b_w_days_of_ride(lazy_df):
        df = lazy_df.with_columns(pl.col("started_at").dt.date().alias("Started_date"))
        daily_counts = df.group_by("Started_date").agg(pl.len().alias("ride_count"))

        daily_counts = daily_counts.with_columns([
            pl.col("Started_date").dt.weekday().alias("day_of_week"),
            (pl.col("Started_date") - pl.duration(days=7)).alias("last_week_date")
        ])

        result = daily_counts.join(
            daily_counts.select([
                pl.col("Started_date").alias("last_week_date"),
                pl.col("ride_count").alias("last_week_ride_count")
            ]),
            on="last_week_date",
            how="left"
        ).with_columns([
            (pl.col("ride_count").cast(pl.Int32) - pl.col("last_week_ride_count").cast(pl.Int32)).alias("diff_vs_last_week")
        ]).select([
            "Started_date", "day_of_week", "ride_count", "last_week_ride_count", "diff_vs_last_week"
        ]).collect()

        result.write_csv("Results/Diff_b_w_current_and_last_weeks_day.csv", include_header=True)
        return result

    # Execute pipeline
    lazy_df = dtypes_checking_and_updating()
    print("Original_Dataframe:- ",lazy_df.collect())
    print("Count of bike rides per Day:- ",count_number_of_bike_rides_per_day(lazy_df))
    print("Avg_Max_Min_number_of_Rides:- ", avg_max_min_number_of_rides_per_week(lazy_df))
    print("diff_b_w_days_of_ride:- ", diff_b_w_days_of_ride(lazy_df))


if __name__ == "__main__":
    main()

Original_Dataframe:-  shape: (999, 13)
┌────────────┬────────────┬────────────┬───────────┬───┬───────────┬─────────┬─────────┬───────────┐
│ ride_id    ┆ rideable_t ┆ started_at ┆ ended_at  ┆ … ┆ start_lng ┆ end_lat ┆ end_lng ┆ member_ca │
│ ---        ┆ ype        ┆ ---        ┆ ---       ┆   ┆ ---       ┆ ---     ┆ ---     ┆ sual      │
│ cat        ┆ ---        ┆ datetime[μ ┆ datetime[ ┆   ┆ f64       ┆ f64     ┆ f64     ┆ ---       │
│            ┆ str        ┆ s]         ┆ μs]       ┆   ┆           ┆         ┆         ┆ str       │
╞════════════╪════════════╪════════════╪═══════════╪═══╪═══════════╪═════════╪═════════╪═══════════╡
│ 6F1682AC40 ┆ electric_b ┆ 2023-06-05 ┆ 2023-06-0 ┆ … ┆ -87.69    ┆ 41.91   ┆ -87.7   ┆ member    │
│ EB6F71     ┆ ike        ┆ 13:34:12   ┆ 5         ┆   ┆           ┆         ┆         ┆           │
│            ┆            ┆            ┆ 14:31:56  ┆   ┆           ┆         ┆         ┆           │
│ 622A1686D6 ┆ electric_b ┆ 2023-06-05 ┆ 2023-06-0 ┆ … ┆ -87.65    ┆ 41.94   ┆ -87.65  ┆ member    │
│ 4948EB     ┆ ike        ┆ 01:30:22   ┆ 5         ┆   ┆           ┆         ┆         ┆           │
│            ┆            ┆            ┆ 01:33:06  ┆   ┆           ┆         ┆         ┆           │
│ 3C88859D92 ┆ electric_b ┆ 2023-06-20 ┆ 2023-06-2 ┆ … ┆ -87.68    ┆ 41.92   ┆ -87.63  ┆ member    │
│ 6253B4     ┆ ike        ┆ 18:15:49   ┆ 0         ┆   ┆           ┆         ┆         ┆           │
│            ┆            ┆            ┆ 18:32:05  ┆   ┆           ┆         ┆         ┆           │
│ EAD8A5E025 ┆ electric_b ┆ 2023-06-19 ┆ 2023-06-1 ┆ … ┆ -87.65    ┆ 41.98   ┆ -87.66  ┆ member    │
│ 9DEC88     ┆ ike        ┆ 14:56:00   ┆ 9         ┆   ┆           ┆         ┆         ┆           │
│            ┆            ┆            ┆ 15:00:35  ┆   ┆           ┆         ┆         ┆           │
│ 5A36F21930 ┆ electric_b ┆ 2023-06-19 ┆ 2023-06-1 ┆ … ┆ -87.66    ┆ 41.99   ┆ -87.65  ┆ member    │
│ D6A55C     ┆ ike        ┆ 15:03:34   ┆ 9         ┆   ┆           ┆         ┆         ┆           │
│            ┆            ┆            ┆ 15:07:16  ┆   ┆           ┆         ┆         ┆           │
│ …          ┆ …          ┆ …          ┆ …         ┆ … ┆ …         ┆ …       ┆ …       ┆ …         │
│ 3B780A995A ┆ electric_b ┆ 2023-06-18 ┆ 2023-06-1 ┆ … ┆ -87.72    ┆ 41.97   ┆ -87.73  ┆ member    │
│ 0219E3     ┆ ike        ┆ 08:32:16   ┆ 8         ┆   ┆           ┆         ┆         ┆           │
│            ┆            ┆            ┆ 08:39:34  ┆   ┆           ┆         ┆         ┆           │
│ 73EAB52DC6 ┆ electric_b ┆ 2023-06-18 ┆ 2023-06-1 ┆ … ┆ -87.67    ┆ 41.92   ┆ -87.68  ┆ member    │
│ 92D9A1     ┆ ike        ┆ 01:07:38   ┆ 8         ┆   ┆           ┆         ┆         ┆           │
│            ┆            ┆            ┆ 01:14:07  ┆   ┆           ┆         ┆         ┆           │
│ EAC18E1F19 ┆ electric_b ┆ 2023-06-17 ┆ 2023-06-1 ┆ … ┆ -87.68    ┆ 41.92   ┆ -87.68  ┆ member    │
│ E5A05B     ┆ ike        ┆ 20:24:58   ┆ 7         ┆   ┆           ┆         ┆         ┆           │
│            ┆            ┆            ┆ 20:25:08  ┆   ┆           ┆         ┆         ┆           │
│ DB04F0278D ┆ electric_b ┆ 2023-06-18 ┆ 2023-06-1 ┆ … ┆ -87.69716 ┆ 41.9    ┆ -87.66  ┆ member    │
│ 4E085B     ┆ ike        ┆ 17:47:30   ┆ 8         ┆   ┆           ┆         ┆         ┆           │
│            ┆            ┆            ┆ 18:01:14  ┆   ┆           ┆         ┆         ┆           │
│ E113CD59DB ┆ electric_b ┆ 2023-06-29 ┆ 2023-06-2 ┆ … ┆ -87.66    ┆ 41.95   ┆ -87.66  ┆ member    │
│ 0D940A     ┆ ike        ┆ 10:24:37   ┆ 9         ┆   ┆           ┆         ┆         ┆           │
│            ┆            ┆            ┆ 10:30:05  ┆   ┆           ┆         ┆         ┆           │
└────────────┴────────────┴────────────┴───────────┴───┴───────────┴─────────┴─────────┴───────────┘
Count of bike rides per Day:-  shape: (30, 2)
┌──────────────┬───────┐
│ Started_date ┆ count │
│ ---          ┆ ---   │
│ date         ┆ u32   │
╞══════════════╪═══════╡
│ 2023-06-24   ┆ 34    │
│ 2023-06-10   ┆ 50    │
│ 2023-06-20   ┆ 28    │
│ 2023-06-26   ┆ 21    │
│ 2023-06-09   ┆ 45    │
│ …            ┆ …     │
│ 2023-06-29   ┆ 26    │
│ 2023-06-25   ┆ 39    │
│ 2023-06-14   ┆ 16    │
│ 2023-06-06   ┆ 22    │
│ 2023-06-01   ┆ 43    │
└──────────────┴───────┘
Avg_Max_Min_number_of_Rides:-  shape: (1, 3)
┌───────────────┬───────────┬───────────┐
│ Average_Rides ┆ Max_rides ┆ Min_rides │
│ ---           ┆ ---       ┆ ---       │
│ f64           ┆ u32       ┆ u32       │
╞═══════════════╪═══════════╪═══════════╡
│ 199.8         ┆ 286       ┆ 142       │
└───────────────┴───────────┴───────────┘
diff_b_w_days_of_ride:-  shape: (30, 5)
┌──────────────┬─────────────┬────────────┬──────────────────────┬───────────────────┐
│ Started_date ┆ day_of_week ┆ ride_count ┆ last_week_ride_count ┆ diff_vs_last_week │
│ ---          ┆ ---         ┆ ---        ┆ ---                  ┆ ---               │
│ date         ┆ i8          ┆ u32        ┆ u32                  ┆ i32               │
╞══════════════╪═════════════╪════════════╪══════════════════════╪═══════════════════╡
│ 2023-06-03   ┆ 6           ┆ 33         ┆ null                 ┆ null              │
│ 2023-06-02   ┆ 5           ┆ 40         ┆ null                 ┆ null              │
│ 2023-06-11   ┆ 7           ┆ 13         ┆ 26                   ┆ -13               │
│ 2023-06-23   ┆ 5           ┆ 45         ┆ 33                   ┆ 12                │
│ 2023-06-04   ┆ 7           ┆ 26         ┆ null                 ┆ null              │
│ …            ┆ …           ┆ …          ┆ …                    ┆ …                 │
│ 2023-06-01   ┆ 4           ┆ 43         ┆ null                 ┆ null              │
│ 2023-06-27   ┆ 2           ┆ 20         ┆ 28                   ┆ -8                │
│ 2023-06-08   ┆ 4           ┆ 16         ┆ 43                   ┆ -27               │
│ 2023-06-18   ┆ 7           ┆ 29         ┆ 13                   ┆ 16                │
│ 2023-06-05   ┆ 1           ┆ 31         ┆ null                 ┆ null              │
└──────────────┴─────────────┴────────────┴──────────────────────┴───────────────────┘