In [1]:
import os
import json

path_to_json_files = 'data/'
json_file_names = [filename for filename in os.listdir(path_to_json_files) if filename.endswith('.json')]
for json_file_name in json_file_names:
    with open(os.path.join(path_to_json_files, json_file_name), 'r') as file:
        data = json.load(file)
        print(data)

{'name': 'Aachen', 'id': '1', 'nametype': 'Valid', 'recclass': 'L5', 'mass': '21', 'fall': 'Fell', 'year': '1880-01-01T00:00:00.000', 'reclat': '50.775000', 'reclong': '6.083330', 'geolocation': {'type': 'Point', 'coordinates': [6.08333, 50.775]}}

In [3]:
from pathlib import Path
import pandas as pd
files = Path("data/").rglob("**/*.json")
for file in files:
    df = pd.read_json(file)

In [4]:
df.head()

,name,id,nametype,recclass,mass,fall,year,reclat,reclong,geolocation
type,Aarhus,2,Valid,H6,720,Fell,1951-01-01T00:00:00.000,56.18333,10.23333,Point
coordinates,Aarhus,2,Valid,H6,720,Fell,1951-01-01T00:00:00.000,56.18333,10.23333,"[10.23333, 56.18333]"

In [9]:
from pathlib import Path
def find_files():
    path = Path("data/")
    return list(path.rglob("*.json"))

In [10]:
find_files()

[PosixPath('data/file-1.json'),
 PosixPath('data/other_folder/file-3.json'),
 PosixPath('data/enough_already/file-4.json'),
 PosixPath('data/.ipynb_checkpoints/file-1-checkpoint.json'),
 PosixPath('data/some_folder/other_folder/file-2.json')]

In [24]:
from pathlib import Path
import glob
files = Path("data/").glob("**/*.json")
for file in files:
    print(file)

data/file-1.json
data/other_folder/file-3.json
data/enough_already/file-4.json
data/.ipynb_checkpoints/file-1-checkpoint.json
data/some_folder/other_folder/file-2.json

In [23]:
df

,name,id,nametype,recclass,mass,fall,year,reclat,reclong,geolocation
type,Aachen,1,Valid,L5,21,Fell,1880-01-01T00:00:00.000,50.775,6.08333,Point
coordinates,Aachen,1,Valid,L5,21,Fell,1880-01-01T00:00:00.000,50.775,6.08333,"[6.08333, 50.775]"

In [27]:
files = glob.glob('data/**/*.json', recursive=True)
files

['data/file-1.json',
 'data/some_folder/other_folder/file-2.json',
 'data/other_folder/file-3.json',
 'data/enough_already/file-4.json']

In [30]:
for i in files:
    print(i)

data/file-1.json
data/some_folder/other_folder/file-2.json
data/other_folder/file-3.json
data/enough_already/file-4.json

In [43]:
import json
import os

def main():
    path = os.path.join(os.getcwd(), "Converted_to_csv")
    os.makedirs(path, exist_ok=True)

    files = glob.glob('data/**/*.json', recursive=True)
    for i in files:
        file_name_with_Ext = i.split('/')[-1]
        file_name = file_name_with_Ext.split('.')[0]
        with open(i) as f:
            d = json.load(f)
            
            n = pd.json_normalize(d)
            n.to_csv("Converted_to_csv/{}.csv".format(file_name),index=False)


if __name__ == "__main__":
    main()

In [ ]:
pd.json_normalize